### PR TITLE
chore: ignore lints on generated crate

### PR DESCRIPTION
**Pull request by m1guelpf**
*Issue #, if available:* N/A

*Description of changes:* When playing around with Pavex, I added this to declutter my `rust-analyzer` suggestions without touching the generated code. Thought it'd be interesting to propose upstream, since it gives the user more options on what to avoid (vs changing a file that will get overwritten). Another option would be to add these to the top of the generated file along with `unused_imports`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by LukeMathWalker** [comment]
We definitely want to allow all `clippy` lints.

I don't feel the same about Rust warnings: the generated code shouldn't trigger any. This is currently violated for the request body, which is bound even if unused. We have a system to annotate with a scoped `#[allow]` already in place for the route params. We just need to apply it there as well.

To move forward on this PR: let's restrict to `clippy`, and you then need to update the snapshot shown in the docs. We don't want the `lints` section to appear there.

**Comment by m1guelpf** [comment]
@LukeMathWalker Updated, do you think it makes sense to keep the allow on Cargo.toml, or should it be moved into the top of the codegen as well?

**Comment by LukeMathWalker** [comment]
Yeah, that's fine in `Cargo.toml`.

For the snapshot: we _don't_ want to show the `lints` table there, because it's not relevant in that section of the documentation. You need to update the extracted range in https://github.com/LukeMathWalker/pavex/blob/f9f6d8feae2847c23993d3e0aae82b678d5f7bd2/doc_examples/quickstart/tutorial.yml#L15 to exclude those lines.

I apologise but I don't have contributor docs at the moment on the docs part, which is a bit involved 😅

**Comment by m1guelpf** [comment]
@LukeMathWalker no problem, I know I'm not really supposed to be using pavex yet either, just thought I'd take advantage of the christmas break to build something 😈

**Pull request merged**
