### PR TITLE
Add graceful shutdown on `Ctrl + C` to template

### PR DESCRIPTION
**Pull request by jehrhardt**
Handling `Ctrl + C` to gracefully shutdown the server is important to ensure a Docker container shuts down properly. The examples and templates should include this to make it easy to get it right.

### CODE REVIEW

**Comment by LukeMathWalker** [comment]
It looks good!
One improvement I'd like to have: let's make the shutdown timeout configurable. We need to add a `graceful_shutdown_timeout_seconds: u64` field to https://github.com/LukeMathWalker/pavex/blob/d699c5f971dc831b2bea54df8a155ac9b125662e/libs/pavexc_cli/template/server/src/configuration/schema.rs#L116 with a 60 seconds default.

**Comment by LukeMathWalker** [comment]
Even better, we can do `graceful_shutdown_timeout` and use [`humantime_serde`](https://docs.rs/humantime-serde/latest/humantime_serde/) for parsing. This allows specifying `2min` as a duration in config, which is much more readable.

**Comment by wuvs** [comment]
imports in examples and template are missing

```rust
use std::time::Duration;
use pavex::server::{ServerHandle, ShutdownMode};
```

**Comment by jehrhardt** [comment]
@LukeMathWalker I added the config via humantime_serde.

**Comment by jehrhardt** [comment]
> imports in examples and template are missing

@wuvs thanks, it should be fixed now.

**Review by jehrhardt — COMMENTED** [review]
Looks like I still missed this import in the examples.

**Comment by LukeMathWalker** [comment]
I was fixing them on my local branch 😁

**Pull request merged**
